<center><h1 style="color:#173F8A;"> Metodos para Ecuaciones Diferenciales, IMT3410, 2023-2 </h1></center>
<h3 style="color:#173F8A;text-align:right;"> Instituto de Ingenieria Matematica y Computacional<br>  Pontificia Universidad Catolica de Chile <br>  </h3>
<h3 style="color:#0176DE;text-align:right;"> Profesor. Manuel A. Sanchez<br> </h3>
<hr style="border:2px solid #03122E"> </hr>

<!-- Palette colors UC: celeste:#0176DE, azul #173F8A, azul oscuro: #03122E, amarillo: #FEC60D, amarillo oscuro: #E3AE00 -->
<!--
<figure>
<img align ="right" src="IMClogo.png" alt="logo" width="250" height="400"><br><br><br><br><br>
</figure>
 -->

## Capitulo 2: Mi primer codigo de elementos finitos

## Problema: 
Queremos resolver la siguiente ecuacion eliptica
$$
-\frac{d}{dx}\left( p(x) \frac{d}{dx}u(x)\right) + r(x)u(x) = f(x),\quad x\in (a,b)
$$
con condiciones de borde $u(a) = A, u(b) = B$.

In [2]:
import numpy as np

In [29]:
# Datos
class problem1delliptic:
    def __init__(self,a,b,f,A,B,p,r,uexact=None,duexact=None):
        self.a = a
        self.b = b
        self.f = f
        self.A = A
        self.B = B
        self.p = p 
        self.r = r
        self.uexact = uexact
        self.duexact = duexact
# problema ejemplo
a = 0.0; b= 1.0
f = lambda x: 0 +0*x
A = 0; B = 0
p = lambda x: 1.0+0*x
r = lambda x: 0+0*x
problema1 = problem1delliptic(a,b,f,A,B,p,r)

In [30]:
# Triangulacion o subdivision del intervalo
class Triangulation1d:
    def __init__(self, Coordinates, Elements1d):
        self.Coordinates = Coordinates
        self.Elements = Elements1d
        self.NN = Coordinates.size
        self.NE = Elements1d.shape[0]
# ejemplo de triangulacion
npoints = 5
x = np.random.rand(npoints-2); z = a + (b-a)*x
Coordinates = np.concatenate( (np.array([a]),np.sort(z),np.array([b])) )
Elements1d = np.asarray([[i, i+1] for i in range(npoints-1)])
mesh1d = Triangulation1d(Coordinates, Elements1d)

In [31]:
def myfirstfem1d(problem, mesh):
    # Matrix 
    A = np.zeros((mesh.NN, mesh.NN), dtype=np.float64)
    # vector
    b = np.zeros(mesh.NN, dtype=np.float64)
    # solution
    uh = np.zeros(mesh.NN, dtype=np.float64)
    # Loop over elements
    for j in range(mesh.NE):
        # element
        K = mesh.Coordinates[mesh.Elements[j,:]]
        # local stiffness matrix
        SK = computeStiffness1d(K,problem.p)
        # local mas matrix 
        MK = computeMass1d(K,problem.r)
        # local assembling matrix A+= AK = SK+MK
        
        # load vector
        bK = computeloadvector1d(K, problem.f)
        # local assembling vector b += bK
    # end loop
    
    # Dirichlet boundary condicion
    uh[0] = A; uh[-1] = B
    b = b - A.dot(uh)
    Freenodes = np.arange(1, mesh.NN-1, dtype=int)
    # slicing
    AFree = A[np.ix_(Freenodes, Freenodes)]  
    # solve linear system AFree uh[Free] = b[Free] 
    return uh

def computeStiffness1d(K,p):
    # compute integral p(x)*phi_i'*phi_j' dx
    SK = np.zeros((2,2),dtype=np.float64)
    return SK
def computeMass1d(K,p):
    # compute integral r(x)*phi_i*phi_j dx
    MK = np.zeros((2,2),dtype=np.float64)
    return MK
def computeloadvector1d(K,p):
    # compute integral f(x)*phi_i dx
    bK = np.zeros(2,dtype=np.float64)
    return bK

In [32]:
A = np.random.rand( mesh1d.NN, mesh1d.NN)
Freenodes = np.arange(1, mesh1d.NN-1, dtype=int)
AFree = A[np.ix_(Freenodes, Freenodes)] 
print(A)
print(AFree)

[[0.88133948 0.03166487 0.34851895 0.45037518 0.47585288]
 [0.88615195 0.25024595 0.9685906  0.77367568 0.58290157]
 [0.98662751 0.09015614 0.90524608 0.34640079 0.8945499 ]
 [0.35503306 0.96447629 0.35695102 0.97651532 0.62180014]
 [0.24859032 0.25322872 0.85722918 0.36987591 0.22548218]]
[[0.25024595 0.9685906  0.77367568]
 [0.09015614 0.90524608 0.34640079]
 [0.96447629 0.35695102 0.97651532]]


In [2]:
lista = ['Ernesto', 'Cesar', 'Gustavo', 'Sebastian','Vicente', 'Patricio', 'Juan Pablo', 'Diego']
import random

def crear_grupos(lista, n):
    N = len(lista)
    random.shuffle(lista)
    Grupos = []
    for j in range(int(N/n)):
        Grupoj = lista[n*j:n*(j+1)]
        Grupos.append(Grupoj)
        print(f"Grupo {j+1} es  {Grupoj}")
crear_grupos(lista,n=2)

Grupo 1 es  ['Diego', 'Juan Pablo']
Grupo 2 es  ['Cesar', 'Vicente']
Grupo 3 es  ['Sebastian', 'Patricio']
Grupo 4 es  ['Ernesto', 'Gustavo']
