<center><h1 style="color:#173F8A;"> Metodos para Ecuaciones Diferenciales, IMT3410, 2023-2 </h1></center>
<h3 style="color:#173F8A;text-align:right;"> Instituto de Ingenieria Matematica y Computacional<br>  Pontificia Universidad Catolica de Chile <br>  </h3>
<h3 style="color:#0176DE;text-align:right;"> Profesor. Manuel A. Sanchez<br> </h3>
<hr style="border:2px solid #03122E"> </hr>

<!-- Palette colors UC: celeste:#0176DE, azul #173F8A, azul oscuro: #03122E, amarillo: #FEC60D, amarillo oscuro: #E3AE00 -->
<!--
<figure>
<img align ="right" src="IMClogo.png" alt="logo" width="250" height="400"><br><br><br><br><br>
</figure>
 -->

## Capitulo 2: Mi primer codigo de elementos finitos

## Problema: 
Queremos resolver la siguiente ecuacion eliptica
$$
-\frac{d}{dx}\left( p(x) \frac{d}{dx}u(x)\right) + r(x)u(x) = f(x),\quad x\in (a,b)
$$
con condiciones de borde $u(a) = A, u(b) = B$.

In [2]:
import numpy as np

In [4]:
# Datos
class problem1delliptic:
    def __init__(self,a,b,f,A,B,p,r,uexact=None):
        self.a = a
        self.b = b
        self.f = f
        self.A = A
        self.B = B
        self.p = p 
        self.r = r
# problema ejemplo
a = 0.0; b= 1.0
f = lambda x: 0 +0*x
A = 0; B = 0
p = lambda x: 1.0+0*x
r = lambda x: 0+0*x
problema1 = problem1delliptic(a,b,f,A,B,p,r)

In [23]:
# Triangulacion o subdivision del intervalo
class Triangulation1d:
    def __init__(self, Coordinates, Elements1d):
        self.Coordinates = Coordinates
        self.Elements = Elements1d
        self.NN = Coordinates.size
        self.NE = Elements1d.shape[0]
# ejemplo de triangulacion
npoints = 5
x = np.random.rand(npoints-2); z = a + (b-a)*x
Coordinates = np.concatenate( (np.array([a]),np.sort(z),np.array([b])) )
Elements1d = np.asarray([[i, i+1] for i in range(npoints-1)])
mesh1d = Triangulation1d(Coordinates, Elements1d)

In [28]:
def myfirstfem1d(problem, mesh):
    # Matrix 
    A = np.zeros((mesh.NN, mesh.NN), dtype=np.float64)
    # vector
    b = np.zeros(mesh.NN, dtype=np.float64)
    # solution
    uh = np.zeros(mesh.NN, dtype=np.float64)
    # Loop over elements
    for j in range(mesh.NE):
        # element
        K = mesh.Coordinates[mesh.Elements[j,:]]
        # local stiffness matrix
        SK = computeStiffness1d(K,problem.p)
        # local mas matrix 
        MK = computeMass1d(K,problem.r)
        # local assembling matrix A+= AK = SK+MK
        
        # load vector
        bK = computeloadvector1d(K, problem.f)
        # local assembling vector b += bK
    # end loop
    
    # Dirichlet boundary condicion
    uh[0] = A; uh[-1] = B
    b = b - A.dot(uh)
    Freenodes = np.arange(1, mesh.NN-1, dtype=int)
    # slicing
    AFree = A[np.ix_(Freenodes, Freenodes)]  
    # solve linear system AFree uh[Free] = b[Free] 
    return uh

def computeStiffness1d(K,p):
    # compute integral p(x)*phi_i'*phi_j' dx
    SK = np.zeros((2,2),dtype=np.float64)
    return SK
def computeMass1d(K,p):
    # compute integral r(x)*phi_i'phi_j dx
    MK = np.zeros((2,2),dtype=np.float64)
    return MK
def computeloadvector1d(K,p):
    # compute integral f(x)*phi_i dx
    bK = np.zeros(2,dtype=np.float64)
    return bK

In [26]:
A = np.random.rand( mesh1d.NN, mesh1d.NN)
Freenodes = np.arange(1, mesh1d.NN-1, dtype=int)
AFree = A[np.ix_(Freenodes, Freenodes)] 
print(A)
print(AFree)

[[0.57510134 0.47870558 0.05778029 0.1709081  0.37071789]
 [0.16660898 0.83407496 0.84149606 0.23714954 0.78073719]
 [0.11142165 0.33446484 0.80559574 0.84589496 0.10968945]
 [0.01410765 0.12973583 0.63675083 0.24637815 0.73319625]
 [0.98142902 0.19499955 0.15112318 0.72103995 0.66692723]]
[[0.83407496 0.84149606 0.23714954]
 [0.33446484 0.80559574 0.84589496]
 [0.12973583 0.63675083 0.24637815]]
